### ISSUE TITLE
for multiple users system auto choose port and port auto cleanup 

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/vcdat#160]

**Comment by James-Crean** [comment]
It turns out that changing the port affects the "Same Origin Policy". This means that the following can happen fairly easily:
1. A user starts vCDAT and port 5000 is open
2. They create some bookmarks that save to LocalStorage
3. They close vCDAT
4. Later, they open vCDAT, but port 5000 is closed, so the app gets port 5001 instead.
5. All of the information in LocalStorage is now blank because the browser considers the different ports to be different sites. 

It looks like we need a different solution to storing bookmarks besides LocalStorage.
